CREATE TABLE users(
id BIGSERIAL PRIMARY KEY,
email VARCHAR(225) NOT NULL UNIQUE,
password_hash VARCHAR(225) NOT NULL,
role VARCHAR(50) NOT NULL,
enabled BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE categories (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
parent_id BIGINT,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_category_parent FOREIGN KEY   (parent_id) REFERENCES categories (id)

);
CREATE TABLE products(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(225) NOT NULL,
description TEXT,
price NUMERIC(10,2) NOT NULL,
category_id BIGINT NOT NULL,
active BOOLEAN NOT NULL DEFAULT TRUE,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES categories (id)

);
